<a href="https://colab.research.google.com/github/Pramodini06/assignment/blob/main/assignment%20day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def matrix_multiply(A, B):
    """
    Perform matrix multiplication using numpy.

    Args:
        A (np.ndarray): First matrix of shape (m, n)
        B (np.ndarray): Second matrix of shape (n, p)

    Returns:
        np.ndarray: Resulting matrix of shape (m, p)
    """
    # Check if shapes are compatible
    if A.shape[1] != B.shape[0]:
        raise ValueError("Incompatible dimensions: A's columns must match B's rows")

    # Perform matrix multiplication
    result = np.dot(A, B)
    return result
 # Define two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Call the function
C = matrix_multiply(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A x B =\n", C)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A x B =
 [[19 22]
 [43 50]]
